const SocketActionTypes = {
   CONNECT: 'CONNECT',
   CHAT_UPDATE: 'CHAT_UPDATE',
   CHAT_DELETE: 'CHAT_DELETE',
   NEW_MESSAGE_INCOME: 'NEW_MESSAGE',
   MESSAGE_UPDATE: 'MESSAGE_UPDATE',
   MESSAGE_DELETE: 'MESSAGE_DELETE'
};

export { SocketActionTypes };
